import { Character } from '../classes/personnage';

export const PERSONNAGES: Character[] = [
  // !!!!!!!!! ATTENTION !!!!!!! Les valeurs strength, luck et endurance ne sont que des valeurs aléatoires pour les tests !!!! A MODIFIER
  {
    _id: '0',
    name: 'Dhareshsaw l\'escargot',
    avatar: './assets/avatars/dhareshsaw.png',
    strength: 4,
    luck: 8,
    endurance: 2,
    items: null,
  },
  {
    _id: '1',
    name: 'Jojo le bourricot',
    avatar: './assets/avatars/johann.png',
    strength: 3,
    luck: 7,
    endurance: 4,
    items: null,
  },
  {
    _id: '2',
    name: 'Anabelle la sauterelle',
    avatar: '',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '3',
    name: 'Bobo le corbeau',
    avatar: '',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '4',
    name: 'Élodie la pie',
    avatar: '',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '5',
    name: 'Hervé le sanglier',
    avatar: '',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '6',
    name: 'Jean-Christo le crapaud',
    avatar: './assets/avatars/jc.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '7',
    name: 'Mathias la limace',
    avatar: './assets/avatars/mathias.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '8',
    name: 'Noémie la fourmi',
    avatar: './assets/avatars/noemie.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '9',
    name: 'Paula le koala',
    avatar: './assets/avatars/paula.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '10',
    name: 'Rapha le lama',
    avatar: './assets/avatars/raph.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '11',
    name: 'Titou le tatou',
    avatar: './assets/avatars/titou.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '12',
    name: 'Vanessa le chat',
    avatar: './assets/avatars/vanessa.png',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
  {
    _id: '13',
    name: 'Yvan l\'habitant',
    avatar: '',
    strength: 3,
    luck: 2,
    endurance: 4,
    items: null,
  },
];
